language: shell

addons:
  apt:
    packages:
    - zsh

script:
- zsh -n .zshrc
- |
  shellcheck \
    --exclude=SC2148 \
    .alias \
    .export \
    .function \
    .path \
    .profile \
    installer.sh
- |
  shfmt -i 2 -l \
    .alias \
    .export \
    .function \
    .path \
    .profile \
    installer.sh
- bats test

