language: shell

os:
- linux
- osx

addons:
  apt:
    packages:
    - zsh

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install shunit2 shellcheck shfmt; fi
  - [[ "$TRAVIS_OS_NAME" == "osx" ]] && SHUNIT2="$(which shunit2)" || SHUNIT2="$HOME/shunit2"
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then curl -L https://github.com/kward/shunit2/releases/download/2.1.8/shunit2 -o "$SHUNIT2" && chmod +x "$SHUNIT2"; fi

script:
- |
  shellcheck \
    --exclude=SC2148 \
    .alias \
    .darwin \
    .export \
    .function \
    .linux \
    .path \
    .profile \
    installer.sh
- |
  shfmt -i 2 -l \
    .alias \
    .darwin \
    .export \
    .function \
    .linux \
    .path \
    .profile \
    installer.sh
- for test in "${HOME}/test/*_tests.sh"; do $SHUNIT2 "${test}"; done

