language: shell

os:
- linux

addons:
  apt:
    packages:
    - shunit2
    - zsh

script:
- |
  shellcheck \
    --exclude=SC2148 \
    .alias \
    .darwin \
    .export \
    .function \
    .linux \
    .path \
    .profile \
    installer.sh
- |
  shfmt -i 2 -l \
    .alias \
    .darwin \
    .export \
    .function \
    .linux \
    .path \
    .profile \
    installer.sh
- for test in "${TRAVIS_BUILD_DIR}"/test/*_tests.sh; do "${test}"; done

