language: shell

os:
- linux
- osx

addons:
  apt:
    packages:
    - zsh

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bats shellcheck shfmt; fi

script:
- |
  shellcheck \
    --exclude=SC2148 \
    .alias \
    .darwin \
    .export \
    .function \
    .linux \
    .path \
    .profile \
    installer.sh
- |
  shfmt -i 2 -l \
    .alias \
    .darwin \
    .export \
    .function \
    .linux \
    .path \
    .profile \
    installer.sh

# Disable bats due to unresolved bug and lack of maintainership.
# https://github.com/sstephenson/bats/issues/140
#
# Might be a good time to switch to shunit2.
# - bats test

